# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# Refer to https://github.com/toml-lang/toml for detailed TOML docs.

required = [
  "github.com/jteeuwen/go-bindata",
]

################################################################################
##                           Framework Dependencies                           ##
################################################################################

[[constraint]]
  name = "github.com/akutz/gofig"
  version = "0.1.9"

[[constraint]]
  name = "github.com/akutz/golf"
  version = "0.1.3"

[[constraint]]
  name = "github.com/akutz/goof"
  version = "0.1.2"

[[constraint]]
  name = "github.com/akutz/gotil"
  version = "0.1.0"

[[constraint]]
  name = "github.com/codedellemc/gournal"
  version = "0.3.1"

[[constraint]]
  name = "github.com/SermoDigital/jose"
  version = "1.1.0"

[[override]]
  name = "github.com/sirupsen/logrus"
  source = "https://github.com/akutz/logrus"
  revision = "d842de504ca841f97533764c59d3166afd70ddb9"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"
[[constraint]]
  name = "github.com/spf13/pflag"
  branch = "master"


################################################################################
##                              Golang/X                                      ##
################################################################################

[[constraint]]
  name = "golang.org/x/crypto"
  branch = "master"

################################################################################
##                              CSI Dependencies                              ##
################################################################################

[[override]]
  name = "github.com/codedellemc/gocsi"
  branch = "master"

[[constraint]]
  name = "github.com/codedellemc/csi-blockdevices"
  branch = "master"

[[constraint]]
  name = "github.com/codedellemc/csi-nfs"
  branch = "master"

[[constraint]]
  name = "github.com/thecodeteam/csi-vfs"
  branch = "master"


################################################################################
##                         Storage Driver Dependencies                        ##
################################################################################

### Amazon
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.34"

### Azure
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~7.0.1-beta"
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "~7.2.2"
[[constraint]]
  name = "github.com/rubiojr/go-vhd"
  revision = "96a0db67ea8209453cfa694bdf03de202d6dd8f8"
  source = "https://github.com/codenrhoden/go-vhd"

### Cinder
[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "b4c2377fa77951a0e08163f52dc9b3e206355194"

### DigitalOcean
[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "1.1.0"

### GCE
[[constraint]]
  name = "google.golang.org/api"
  branch = "master"
[[constraint]]
  name = "google.golang.org/appengine"
  branch = "master"

### Isilon
[[constraint]]
  name = "github.com/codedellemc/goisilon"
  revision = "301d518bb39637b839382deb686811dcf257b8c8"

### ScaleIO
[[constraint]]
  name = "github.com/codedellemc/goscaleio"
  revision = "d9df9f1ff56d951b0d5dfc30c374533ac56a4068"

### VirtualBox
[[constraint]]
  name = "github.com/appropriate/go-virtualboxclient"
  revision = "e0978ab2ed407095400a69d5933958dd260058cd"
  source = "https://github.com/clintonskitson/go-virtualboxclient"


################################################################################
##                                  Tools                                     ##
################################################################################

[[constraint]]
  name = "github.com/jteeuwen/go-bindata"
  source = "https://github.com/akutz/go-bindata"
  revision = "1dd44b25b79c4d9060e582e90798e4d72537818c"


################################################################################
##                                  Go-YAML                                   ##
################################################################################

[[constraint]]
  name = "gopkg.in/yaml.v2"
  source = "https://github.com/akutz/yaml.git"
  revision = "bc35f417f8a7664a73d46c9def2933417c03019f"


################################################################################
##                                 Testing                                    ##
################################################################################

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "1.4.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  branch = "master"
