site_name: REX-Ray
site_url: https://github.com/emccode/rexray
repo_url: https://github.com/emccode/rexray.git
docs_dir: .docs
site_dir: .site
theme_dir: .docs/.themes/yeti
site_favicon: favicon.png

extra_javascript:
    - js/jquery.smartmenus.min.js
    - js/jquery.smartmenus.bootstrap.min.js
extra_css:
    - css/sm-core-css.css
    - css/jquery.smartmenus.bootstrap.css
    - css/emccode-font.css

pages:
- Home: index.md
- User Guide:
    - Installation: user-guide/installation.md
    - Configuration: user-guide/config.md
    - Storage Providers: user-guide/storage-providers.md
    - Schedulers: user-guide/schedulers.md
    - Applications: user-guide/application.md
- Developers Guide:
    - Project Guidelines: dev-guide/project-guidelines.md
    - Build Reference: dev-guide/build-reference.md
    - Release Process: dev-guide/release-process.md
- About:
    - Contributing: about/contributing.md
    - License: about/license.md
    - Release Notes: about/release-notes.md
